kind: pipeline
name: default

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: simple-react
  image: plugins/docker
  repo: dimakharapaev/new
  registry: registry-1.docker.io/v2/
  tags: tag
  Dockerfile: react-project/Dockerfile
  username: dimakharapaev
  password: Dasha@19882
    when:
      branch: master