kind: pipeline
name: default

trigger:
  event:
  - push
  branch:
  - master

steps:

- name: docker  
  image: plugins/docker
  settings:
    username: dimakharapaev
    password: Dasha@19882
    repo: dimakharapaev/new
    insecure: true
    tags: latest2