kind: pipeline
name: api

build_settings: &docker_registry_settings
  username: dimakharapaev
  password: Dasha@19882

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: build-api
  image: plugins/docker
  settings:
    <<: *docker_registry_settings
    repo: dimakharapaev/new
    tags:
      - newLatest
    insecure: true
    context: api
    Dockerfile: REACT-PROJECT/Dockerfile
    command: docker build -t simple-react
    when:
      branch: master