kind: pipeline
name: api

trigger:
  event:
  - push
  branch:
  - master

pipeline:
  docker-build:
    image: plugins/docker
    repo: dimakharapaev/new
    tags: tag
    Dockerfile: react-project/Dockerfile
    username: dimakharapaev
    password: Dasha@19882
    when:
      branch: master